project_id = "bdkdcwfmevyvzxjvmxgt"

[functions.validate-client-token]
verify_jwt = false

[functions.send-contract]
verify_jwt = false

[functions.manage-integration-credentials]
verify_jwt = true

[functions.sync-meta-ads]
verify_jwt = false

[functions.sync-google-ads]
verify_jwt = false

[functions.sync-tiktok-ads]
verify_jwt = false

[functions.sync-all-integrations]
verify_jwt = false