// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdkdcwfmevyvzxjvmxgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJka2Rjd2ZtZXZ5dnp4anZteGd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MzY1ODksImV4cCI6MjA3NDIxMjU4OX0.14AWclcjZAukMlKSCkf934P_gxIMBzjEM6vQF1BwUsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});